services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node src/server.js
    deploy:
      replicas: 8
      restart_policy:
        condition: app
      update_config:
        parallelism: 2
        delay: 15s

  nginx:
    ports:
      - "80:80"
